<?php
/* @var $block Magento\Framework\View\Element\Template */
?>
<div id="free-shipping-banner">
    Free Shipping Banner
</div>

<script type="text/x-magento-init">
    {
        "#free-shipping-banner": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "free-shipping-banner": {
                        "component": "Macademy_FreeShippingPromo/js/free-shipping-banner"
                    }
                }
            }
        }
    }
</script>
